version: "2"

services:

# ------> asset ------>
    asset_e0ywpailjm0esook:
        container_name: asset_e0ywpailjm0esook
        image: node:alpine
        working_dir: /var/www/assets
        volumes:
            - ../assets:/var/www/assets
            - ../public:/var/www/public
# <------ asset <------

# ------> composer ------>
    composer_e0ywpailjm0esool:
        container_name: composer_e0ywpailjm0esool
        image: composer:latest
        volumes:
            - .././:/app
        command: ["composer", "update"]
# <------ composer <------

# ------> mariadb ------>
    mariadb_e0ywpailjm0esoom:
        container_name: mariadb_e0ywpailjm0esoom
        image: mariadb:latest
        restart: always
        volumes:
            - ../../.database/my_app:/var/lib/mysql
#            - ./mariadb/conf/mariadb:/etc/mysql
        environment:
            MYSQL_DATABASE: coding
            MYSQL_USER: coding
            MYSQL_PASSWORD: coding
            MYSQL_ROOT_PASSWORD: coding
# <------ mariadb <------

# ------> symfony ------>
    symfony_e0ywpailjm0esoon:
        container_name: symfony_e0ywpailjm0esoon
        build: ./symfony
        image: skyflow/symfony
        restart: always
        working_dir: /coding-sensei
        ports:
            - 8889:80
        volumes:
            - ../:/coding-sensei
            - ./symfony/conf/apache2:/etc/apache2
            - ./symfony/conf/php7/php.ini:/etc/php7/php.ini
# <------ symfony <------