index:
    path: /
    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check
# the "app_lucky_number" route name is not important yet
Main:
    path: /
    controller: App\Controller\MainController::MainAction

MainDouble:
    path: /{page}
    controller: App\Controller\MainController::MainAction

MainDoubleTriple:
    path: /{page}/{pageDeux}
    controller: App\Controller\MainController::MainAction
